# ==============
# driftfore-dots
# ==============

# Cursor style
cursor			#c9a46a

# Background
foreground 		#c7d0d9
background		#11161c
selection_foreground 	#11161c
selection_background 	#c9a46a

# URL style
url_color		#b08d57
url_style 		single

# Color palate

# Black
color0	#040506
color8	#0b0e11
# Red
color1	#a3320b
color9	#bf3a0d
# Green
color2	#374f2f
color10	#4a6741
# Yellow
color3	#b08d57
color11	#d2b07b
# Blue
color4	#2f9d94
color12	#52cdc1
# Magenta
color5	#6c244c
color13	#b83d81
# Cyan
color6	#7fe7ce
color14	#baf2e5
# White
color7	#c7d0d9
color15	#f4f8fc
