# ===============
# driftforge-dots
# ===============

font_family      FantasqueSansM Nerd Font
italic_font      auto
bold_font        auto
bold_italic_font auto
font_size        13.0

shell_integration 	no-cursor
cursor_shape		beam
cursor			#c9a46a

foreground 		#c7d0d9
background		#11161c

selection_foreground 	#c7d0d9
selection_background 	#c9a46a

url_color		#b08d57

# Color palate

# Black
color0	#040506
color8	#0b0e11

# Red
color1	#b08d57
color9	#c9a46a

# Green
color2	#a7b1ba
color10	#c7d0d9

# Yellow
color3	#b08d57
color11	#d2b07b

# Blue
color4	#a7b1ba
color12	#dcebff

# Magenta
color5	#6e7781
color13	#a7b1ba

# Cyan
color6	#c7d0d9
color14	#eaf2f8

# White
color7	#c7d0d9
color15	#f4f8fc
